[tools]
go = "latest"
node = "lts"
ruby = "3.3.9"
yarn = "latest"

"npm:typescript-language-server" = "latest"
"npm:@gitlab/duo-cli" = "latest"
rust = "1.89.0"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.npm]
bun = true

[settings.ruby]
compile = false
